// Generated by gencpp from file balance/PositionInformation.msg
// DO NOT EDIT!


#ifndef BALANCE_MESSAGE_POSITIONINFORMATION_H
#define BALANCE_MESSAGE_POSITIONINFORMATION_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace balance
{
template <class ContainerAllocator>
struct PositionInformation_
{
  typedef PositionInformation_<ContainerAllocator> Type;

  PositionInformation_()
    : x(0.0)
    , y(0.0)
    , time(0.0)  {
    }
  PositionInformation_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)
    , time(0.0)  {
  (void)_alloc;
    }



   typedef float _x_type;
  _x_type x;

   typedef float _y_type;
  _y_type y;

   typedef double _time_type;
  _time_type time;





  typedef boost::shared_ptr< ::balance::PositionInformation_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::balance::PositionInformation_<ContainerAllocator> const> ConstPtr;

}; // struct PositionInformation_

typedef ::balance::PositionInformation_<std::allocator<void> > PositionInformation;

typedef boost::shared_ptr< ::balance::PositionInformation > PositionInformationPtr;
typedef boost::shared_ptr< ::balance::PositionInformation const> PositionInformationConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::balance::PositionInformation_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::balance::PositionInformation_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace balance

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'balance': ['/home/cc/ee106b/sp22/class/ee106b-acg/Desktop/projects/final_ws/src/balance/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::balance::PositionInformation_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::balance::PositionInformation_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::balance::PositionInformation_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::balance::PositionInformation_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::balance::PositionInformation_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::balance::PositionInformation_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::balance::PositionInformation_<ContainerAllocator> >
{
  static const char* value()
  {
    return "08f6c06eb104dc3528cd793d99e2022d";
  }

  static const char* value(const ::balance::PositionInformation_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x08f6c06eb104dc35ULL;
  static const uint64_t static_value2 = 0x28cd793d99e2022dULL;
};

template<class ContainerAllocator>
struct DataType< ::balance::PositionInformation_<ContainerAllocator> >
{
  static const char* value()
  {
    return "balance/PositionInformation";
  }

  static const char* value(const ::balance::PositionInformation_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::balance::PositionInformation_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 x\n\
float32 y\n\
float64 time\n\
";
  }

  static const char* value(const ::balance::PositionInformation_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::balance::PositionInformation_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.time);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PositionInformation_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::balance::PositionInformation_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::balance::PositionInformation_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<float>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<float>::stream(s, indent + "  ", v.y);
    s << indent << "time: ";
    Printer<double>::stream(s, indent + "  ", v.time);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BALANCE_MESSAGE_POSITIONINFORMATION_H
